# Generated by Django 3.1.5 on 2021-02-04 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Devices',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('imei', models.CharField(max_length=100)),
                ('oaid', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('mac', models.CharField(max_length=100)),
                ('product', models.CharField(max_length=100)),
                ('os', models.CharField(max_length=100)),
                ('cpu', models.CharField(max_length=100)),
                ('api', models.IntegerField()),
                ('sys_ver', models.CharField(max_length=100)),
                ('emulator', models.BooleanField()),
                ('screen', models.CharField(max_length=100)),
                ('last_time', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PopConfig',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('tag', models.CharField(max_length=100)),
                ('width_percent', models.FloatField()),
                ('height_percent', models.FloatField()),
                ('dim_amount', models.FloatField()),
                ('enforce', models.BooleanField()),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('confirm_txt', models.CharField(max_length=100)),
                ('cancel_txt', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('last_login_time', models.BigIntegerField()),
                ('last_update_time', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UserDevices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('devices', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('token', models.TextField()),
                ('update_time', models.BigIntegerField()),
                ('expired_time', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='UpdateInfo',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('new_version_code', models.BigIntegerField()),
                ('new_version_name', models.CharField(max_length=100)),
                ('sign_md5', models.CharField(max_length=200)),
                ('apk_md5', models.CharField(max_length=200)),
                ('apk_size', models.IntegerField()),
                ('new_apk_url', models.CharField(max_length=200)),
                ('ext', models.TextField()),
                ('create_time', models.BigIntegerField()),
                ('last_update_time', models.BigIntegerField()),
                ('author', models.CharField(max_length=100)),
                ('pop_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yikan.popconfig')),
            ],
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('ver', models.BigIntegerField()),
                ('type', models.IntegerField()),
                ('url', models.CharField(max_length=200)),
                ('create_time', models.BigIntegerField()),
                ('author', models.CharField(max_length=100)),
                ('pop_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yikan.popconfig')),
            ],
        ),
    ]
