# Generated by Django 3.1.5 on 2021-02-04 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yikan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='popconfig',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
