# Generated by Django 3.1.5 on 2021-02-04 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yikan', '0003_auto_20210204_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='updateinfo',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='updateinfo',
            name='last_update_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
