# Generated by Django 3.1.5 on 2021-02-05 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yikan', '0006_auto_20210204_1753'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='times',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
